spring:
  zipkin:
    base-url: http://192.168.37.129:9411/
    discovery-client-enabled: false
    sender:
      type: web
  sleuth:
    sampler:
      probability: 1
  cloud:
    nacos:
      discovery:
        server-addr: 192.168.37.129:8848
    sentinel:
      transport:
        dashboard: 192.168.2.249:8080
        port: 8719
  application:
    name: gulimall-auth-server
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
  thymeleaf:
    cache: false
  redis:
    host: 192.168.37.129
    port: 6379
  session:
    store-type: redis
    timeout: 30m
server:
  port: 8086
logging:
  level:
    com.sovava: debug
    org.springframework.cloud.openfeign: debug
    org.springframework.cloud.sleuth: debug
feign:
  sentinel:
    enabled: true