spring:
  application:
    name: gulimall-seckill
  redis:
    host: 192.168.37.129
    port: 6379 # 配置使用redis作为缓存
  cloud:
    nacos:
      discovery:
        server-addr: 192.168.37.129:8848
  task:
    execution:
      pool:
        max-size: 50
  session:
    store-type: redis
    timeout: 30m
  rabbitmq:
    addresses: 192.168.37.129
    port: 5672
    virtual-host: /sovava
    username: sovava
    password: ykn12345!
    #开启发送端确认
    publisher-confirm-type: correlated
    #开启exchange到queue的确认
    publisher-returns: true
    #只要抵达队列 ， 以异步发送优先回调return confirm
    template:
      mandatory: true
    #手动签收
    listener:
      simple:
        acknowledge-mode: manual
  thymeleaf:
    cache: false
logging:
  level:
    com.sovava: debug
server:
  port: 8089