spring:
  application:
    name: gulimall-seckill
  redis:
    host: 192.168.37.129
    port: 6379 # 配置使用redis作为缓存
  cloud:
    nacos:
      discovery:
        server-addr: 192.168.37.129:8848
  task:
    execution:
      pool:
        max-size: 50
logging:
  level:
    com.sovava: debug
server:
  port: 8089