spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: ykn12345
    url: jdbc:mysql://192.168.37.129:3306/gulimall_oms
  rabbitmq:
    addresses: 192.168.37.129
    port: 5672
    virtual-host: /sovava
    username: sovava
    password: ykn12345!
    #开启发送端确认
    publisher-confirm-type: correlated
    #开启exchange到queue的确认
    publisher-returns: true
    #只要抵达队列 ， 以异步发送优先回调return confirm
    template:
      mandatory: true
    #手动签收
    listener:
      simple:
        acknowledge-mode: manual
  cloud:
    nacos:
      discovery:
        server-addr: 192.168.37.129:8848
  application:
    name: gulimall-product
  thymeleaf:
    cache: false
mybatis-plus:
  global-config:
    db-config:
      id-type: auto
  mapper-locations: classpath*:/mapper/**/*.xml
logging:
  level:
    com.sovava: debug
server:
  port: 8088
